<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Fadada.CertificationQueryAgent.Application\Fadada.CertificationQueryAgent.Application.csproj" />
    <ProjectReference Include="..\Fadada.CertificationQueryAgent.AgentHost\Fadada.CertificationQueryAgent.AgentHost.csproj" />
    <ProjectReference Include="..\Fadada.CertificationQueryAgent.Infrastructure\Fadada.CertificationQueryAgent.Infrastructure.csproj" />
    <ProjectReference Include="..\Fadada.CertificationQueryAgent.Infrastructure.SqlServer2012\Fadada.CertificationQueryAgent.Infrastructure.SqlServer2012.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Content Update="appsettings.Local.json">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlSanitizer" />
    <PackageReference Include="Markdig" />
  </ItemGroup>

</Project>
